version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chess
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  python-app:
    build: ./python-app
    container_name: chess
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: chess
    command: tail -F anything

volumes:
  db_data:
