"""empate por insuficiencia material

Revision ID: 2327354f4758
Revises: 953b54a50b5d
Create Date: 2024-09-01 15:42:44.186355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2327354f4758'
down_revision: Union[str, None] = '953b54a50b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posicoes', sa.Column('empate_material_insuficiente', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posicoes', 'empate_material_insuficiente')
    # ### end Alembic commands ###
