"""correcao

Revision ID: 264e1ae1936c
Revises: 8017a7a0232d
Create Date: 2024-08-25 22:02:58.360254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '264e1ae1936c'
down_revision: Union[str, None] = '8017a7a0232d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidas', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidas', sa.Column('descricao', mysql.VARCHAR(length=2048), nullable=False))
    # ### end Alembic commands ###
