"""Adiciona fen_inicial e unique constraint brancas negras e fen_inicial

Revision ID: 30fdf99efc24
Revises: daf3b178e1f5
Create Date: 2024-08-19 11:53:34.153395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fdf99efc24'
down_revision: Union[str, None] = 'daf3b178e1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidas', sa.Column('fen_inicial', sa.String(length=2048), nullable=False))
    op.create_unique_constraint('_brancas_negras_fen_inicial_uc', 'partidas', ['brancas_id', 'negras_id', 'fen_inicial'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_brancas_negras_fen_inicial_uc', 'partidas', type_='unique')
    op.drop_column('partidas', 'fen_inicial')
    # ### end Alembic commands ###
