"""inicia

Revision ID: 500edd34aae6
Revises: 
Create Date: 2024-09-19 00:15:56.594327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500edd34aae6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posicoes', sa.Column('diferenca_material', sa.Integer(), nullable=False))
    op.add_column('posicoes', sa.Column('cavalos_brancas', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('cavalos_negras', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('empate_material_insuficiente', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posicoes', 'empate_material_insuficiente')
    op.drop_column('posicoes', 'cavalos_negras')
    op.drop_column('posicoes', 'cavalos_brancas')
    op.drop_column('posicoes', 'diferenca_material')
    # ### end Alembic commands ###
