"""adiciona tabela de cenarios

Revision ID: 68bb4cbe08ed
Revises: e512745f9abd
Create Date: 2024-08-23 01:18:10.795286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68bb4cbe08ed'
down_revision: Union[str, None] = 'e512745f9abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fen', sa.String(length=2048), nullable=False),
    sa.Column('descricao', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('avaliacoes', 'tempo_segundos',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('partidas', sa.Column('cenario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'partidas', 'cenarios', ['cenario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidas', type_='foreignkey')
    op.drop_column('partidas', 'cenario_id')
    op.alter_column('avaliacoes', 'tempo_segundos',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('cenarios')
    # ### end Alembic commands ###
