"""correcao

Revision ID: 8017a7a0232d
Revises: db4e0724e152
Create Date: 2024-08-25 17:43:22.477138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8017a7a0232d'
down_revision: Union[str, None] = 'db4e0724e152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'partidas', 'jogadores', ['brancas_id'], ['id'])
    op.create_foreign_key(None, 'partidas', 'jogadores', ['negras_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidas', type_='foreignkey')
    op.drop_constraint(None, 'partidas', type_='foreignkey')
    # ### end Alembic commands ###
