"""Added account table

Revision ID: 8365fa8d3725
Revises: 014682f42191
Create Date: 2024-09-02 00:26:34.773485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8365fa8d3725'
down_revision: Union[str, None] = '014682f42191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posicoes', sa.Column('diferenca_material', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posicoes', 'diferenca_material')
    # ### end Alembic commands ###
