"""adiciona id do vencedor na partida

Revision ID: ceda68928ad7
Revises: 500edd34aae6
Create Date: 2024-09-19 12:22:25.898962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceda68928ad7'
down_revision: Union[str, None] = '500edd34aae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidas', sa.Column('vencedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'partidas', 'jogadores', ['vencedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidas', type_='foreignkey')
    op.drop_column('partidas', 'vencedor_id')
    # ### end Alembic commands ###
