"""correcao

Revision ID: db4e0724e152
Revises: ff673ff26dc3
Create Date: 2024-08-25 16:59:48.484792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db4e0724e152'
down_revision: Union[str, None] = 'ff673ff26dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_brancas_negras_fen_inicial_uc', table_name='partidas')
    op.create_unique_constraint('_brancas_negras_cenario_uc', 'partidas', ['brancas_id', 'negras_id', 'cenario_id'])
    op.drop_column('partidas', 'fen_inicial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidas', sa.Column('fen_inicial', mysql.VARCHAR(length=2048), nullable=False))
    op.drop_constraint('_brancas_negras_cenario_uc', 'partidas', type_='unique')
    op.create_index('_brancas_negras_fen_inicial_uc', 'partidas', ['brancas_id', 'negras_id', 'fen_inicial'], unique=True)
    # ### end Alembic commands ###
