"""Adiciona tabela avaliacao e faz ajustes

Revision ID: e512745f9abd
Revises: 30fdf99efc24
Create Date: 2024-08-19 15:40:36.151889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e512745f9abd'
down_revision: Union[str, None] = '30fdf99efc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tempo_segundos', sa.String(length=255), nullable=False),
    sa.Column('melhor_lance', sa.String(length=255), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('posicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.ForeignKeyConstraint(['posicao_id'], ['posicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
