"""Modelagem definitiva

Revision ID: fba3050de0be
Revises: fd851a278f5b
Create Date: 2024-08-18 20:56:56.426365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba3050de0be'
down_revision: Union[str, None] = 'fd851a278f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidas', sa.Column('descricao', sa.String(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidas', 'descricao')
    # ### end Alembic commands ###
