"""Modelagem definitiva

Revision ID: fd851a278f5b
Revises: 77abc44a8de0
Create Date: 2024-08-18 20:50:21.160301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd851a278f5b'
down_revision: Union[str, None] = '77abc44a8de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('profundidade', sa.Integer(), nullable=False),
    sa.Column('redes_neurais', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lances', sa.String(length=2048), nullable=False),
    sa.Column('resultado', sa.String(length=45), nullable=False),
    sa.Column('brancas_id', sa.Integer(), nullable=False),
    sa.Column('negras_id', sa.Integer(), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['brancas_id'], ['jogadores.id'], ),
    sa.ForeignKeyConstraint(['negras_id'], ['jogadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sequencias')
    op.add_column('posicoes', sa.Column('numero_sequencia', sa.Integer(), nullable=False))
    op.add_column('posicoes', sa.Column('rei_brancas', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('rei_negras', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('dama_brancas', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('dama_negras', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('torres_brancas', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('torres_negras', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('bispos_brancas', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('bispos_negras', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('peoes_brancas', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('peoes_negras', sa.JSON(), nullable=False))
    op.add_column('posicoes', sa.Column('check', sa.Integer(), nullable=False))
    op.add_column('posicoes', sa.Column('mate', sa.Integer(), nullable=False))
    op.add_column('posicoes', sa.Column('empate_repeticoes', sa.Integer(), nullable=False))
    op.add_column('posicoes', sa.Column('empate_50', sa.Integer(), nullable=False))
    op.add_column('posicoes', sa.Column('empate_afogamento', sa.Integer(), nullable=False))
    op.add_column('posicoes', sa.Column('partida_id', sa.Integer(), nullable=False))
    op.alter_column('posicoes', 'fen',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=4096),
               existing_nullable=False)
    op.create_foreign_key(None, 'posicoes', 'partidas', ['partida_id'], ['id'])
    op.drop_column('posicoes', 'qbp')
    op.drop_column('posicoes', 'qwn')
    op.drop_column('posicoes', 'qbq')
    op.drop_column('posicoes', 'king_safety')
    op.drop_column('posicoes', 'qbn')
    op.drop_column('posicoes', 'imbalance')
    op.drop_column('posicoes', 'qwr')
    op.drop_column('posicoes', 'mobility')
    op.drop_column('posicoes', 'qwp')
    op.drop_column('posicoes', 'qwb')
    op.drop_column('posicoes', 'material')
    op.drop_column('posicoes', 'evaluation')
    op.drop_column('posicoes', 'qbr')
    op.drop_column('posicoes', 'passed')
    op.drop_column('posicoes', 'qbb')
    op.drop_column('posicoes', 'threats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posicoes', sa.Column('threats', mysql.FLOAT(), nullable=False))
    op.add_column('posicoes', sa.Column('qbb', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posicoes', sa.Column('passed', mysql.FLOAT(), nullable=False))
    op.add_column('posicoes', sa.Column('qbr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posicoes', sa.Column('evaluation', mysql.FLOAT(), nullable=False))
    op.add_column('posicoes', sa.Column('material', mysql.FLOAT(), nullable=False))
    op.add_column('posicoes', sa.Column('qwb', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posicoes', sa.Column('qwp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posicoes', sa.Column('mobility', mysql.FLOAT(), nullable=False))
    op.add_column('posicoes', sa.Column('qwr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posicoes', sa.Column('imbalance', mysql.FLOAT(), nullable=False))
    op.add_column('posicoes', sa.Column('qbn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posicoes', sa.Column('king_safety', mysql.FLOAT(), nullable=False))
    op.add_column('posicoes', sa.Column('qbq', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posicoes', sa.Column('qwn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posicoes', sa.Column('qbp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posicoes', type_='foreignkey')
    op.alter_column('posicoes', 'fen',
               existing_type=sa.String(length=4096),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('posicoes', 'partida_id')
    op.drop_column('posicoes', 'empate_afogamento')
    op.drop_column('posicoes', 'empate_50')
    op.drop_column('posicoes', 'empate_repeticoes')
    op.drop_column('posicoes', 'mate')
    op.drop_column('posicoes', 'check')
    op.drop_column('posicoes', 'peoes_negras')
    op.drop_column('posicoes', 'peoes_brancas')
    op.drop_column('posicoes', 'bispos_negras')
    op.drop_column('posicoes', 'bispos_brancas')
    op.drop_column('posicoes', 'torres_negras')
    op.drop_column('posicoes', 'torres_brancas')
    op.drop_column('posicoes', 'dama_negras')
    op.drop_column('posicoes', 'dama_brancas')
    op.drop_column('posicoes', 'rei_negras')
    op.drop_column('posicoes', 'rei_brancas')
    op.drop_column('posicoes', 'numero_sequencia')
    op.create_table('sequencias',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_posicao', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ordem', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fen', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('evaluation', mysql.FLOAT(), nullable=False),
    sa.Column('imbalance', mysql.FLOAT(), nullable=False),
    sa.Column('material', mysql.FLOAT(), nullable=False),
    sa.Column('mobility', mysql.FLOAT(), nullable=False),
    sa.Column('king_safety', mysql.FLOAT(), nullable=False),
    sa.Column('threats', mysql.FLOAT(), nullable=False),
    sa.Column('passed', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_posicao'], ['posicoes.id'], name='sequencias_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('partidas')
    op.drop_table('jogadores')
    op.drop_table('ambientes')
    # ### end Alembic commands ###
